apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: llamaforge

resources:
  - namespace.yaml
  - redis.yaml
  - postgres.yaml
  - github-app-deployment.yaml
  - service-api-deployment.yaml
  - worker-deployment.yaml
  - network-policies.yaml
  - route-service-api.yaml

images:
  - name: ghcr.io/akram/llamaforge/github-app
    newTag: latest
  - name: ghcr.io/akram/llamaforge/service-api
    newTag: latest
  - name: ghcr.io/akram/llamaforge/worker
    newTag: latest

